apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 730335582955.dkr.ecr.us-east-1.amazonaws.com/shopping-site-phones:e1cd5a53454a13cd9cd431f822042f1495587679
        ports:
        - containerPort: 80
